version: "3"
services:
    cliceat-services:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: cliceat-services
        container_name: cliceat-services
        ports:
            - "8500:80"
        volumes:
            - ./:/var/www/html
            - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - cliceat-services
        depends_on:
            - cliceat-services-mysql

    cliceat-services-mysql:
        restart: always
        image: mysql:8.0
        cap_add:
            - SYS_NICE
        environment:
          MYSQL_DATABASE: 'cliceat'
      # So you don't have to use root, but you can if you like
          MYSQL_USER: 'root'
      # You can use whatever password you like
          MYSQL_PASSWORD: 'root'
      # Password for root access
          MYSQL_ROOT_PASSWORD: 'root'
        ports:
      # <Port exposed> : <MySQL Port running inside container>
          - '8501:3306'
      # Where our data will be persisted
        volumes:
          - cliceat-db:/var/lib/mysql
          - ./cliceat-db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
    cliceat-services:
        driver: bridge
volumes:
    cliceat-db:
        driver: local