version: "3.8"
services:
    cliceat-services:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: cliceat-services
        container_name: cliceat-services
        ports:
            - "8500:80"
        volumes:
            - ./:/var/www/html
            - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - cliceat-services
        depends_on:
            - cliceat-services-mysql

    cliceat-services-mysql:
        image: mysql:8.0
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            - MYSQL_DATABASE=cliceat
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - '8501:3306'
        volumes:
            - db:/var/lib/mysql
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
    cliceat-services:
        driver: bridge
volumes:
    db:
        driver: local