version: "3"
services:
    clieat-services:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: clieat-services
        container_name: clieat-services
        ports:
            - "8500:80"
        volumes:
            - ./:/var/www/html
            - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - clieat-services
        depends_on:
            - clieat-services-mysql

    clieat-services-mysql:
        restart: always
        image: mysql:5.7
        environment:
          MYSQL_DATABASE: 'clieat'
      # So you don't have to use root, but you can if you like
          MYSQL_USER: 'root'
      # You can use whatever password you like
          MYSQL_PASSWORD: 'root'
      # Password for root access
          MYSQL_ROOT_PASSWORD: 'root'
        ports:
      # <Port exposed> : <MySQL Port running inside container>
          - '8501:3306'
        expose:
      # Opens port 3306 on the container
          - '3306'
      # Where our data will be persisted
        volumes:
          - my-db:/var/lib/mysql

networks:
    clieat-services:
        driver: bridge
volumes:
    my-db: